#+title: About this site
#+hugo_section: about

#+date: 2021-10-02
#+hugo_tags: org hugo
#+hugo_categories: meta
#+hugo_publishdate: 2021-10-02
#+hugo_auto_set_lastmod: t
#+hugo_custom_front_matter: :math false
#+hugo_auto_set_lastmod: t


In which I give the requisite grandiloquent soliloquy about how this
site is made.

#+hugo: more

* Purpose and intent

Many times in the past I have attempted to make a "web site" that is
somehow [[/about/me][about me]].  This is the latest.  Time will tell if it survives.

This site is intended as an outlet for:

- Detailed responses to technical inquires that might otherwise go
  into an individual email message.  Seeking "efficiency" (laziness) I
  may instead turn a response into a [[/posts][blog post]] or a more formal
  [[/articles][article]] (such as [[/articles/howido][howido]]).  Where applicable, some things already
  land in [[https://wirecell.github.io/news/][Wire-Cell News]] posts.

- I want a way to distribute information which has some amount of
  independent from my employer be it related to physics, software or
  other topics not appropriately served from a ~.gov~ address.  Thus,
  this site will not be served from my [[https://www.phy.bnl.gov/~bviren/][BNL web area]] (which I mostly
  use for random file distribution, especially in a very permanent
  [[https://www.phy.bnl.gov/~bviren/tmp/][tmp/]]).

- Remembering all my past activities is becoming a chore and noting
  them down will hopefully make that easy.  Thus some posts may be
  rather boring, as they will be literally web logs.  They will be
  kept distinct from more interesting items in some manner (likely in
  a "notes" section).

- When solving problems I tend to talk to myself using fingers typing
  instead of lips flapping.  Putting these thoughts on this help me
  focus them and find them later.  Maybe.  I also tend to revisit so
  expect you may see here to change over time.

* Organization

Following Hugo nomenclature the site is organized first by /sections/.
Sections are interpreted as a type or a form of page.  The following
sections may be found:

- [[file:/about/][about]] :: meta descriptions (ie, this site),
- [[file:/posts/][posts]] :: short "blog" entries, unlikely to (but may) see updates,
- [[file:/articles/][articles]] :: long form on a topic and potentially updated over time.
- [[/notes][notes]] :: things likely more interesting to myself than others which is meant to summarize or simply mark some occurrence. 

All /pages/ in these sections may have one or more /category/ or /tag/.  In
Hugo these are both /taxonomies/.  They are provided by Hugo with no
assumed interpretation and so these are taken:

- [[file:/categories/][categories]] :: A limited number of general descriptors defined in a top-down manner.  These label the basic topical subject of the page independent of its section.
- [[file:/tags/][tags]] :: Numerous, unbound set of detailed descriptors defined in a bottom-up manner as pages are written.  These label aspects of the content regardless of category or section.

* Tech

This blog uses [[https://www.gnu.org/software/emacs/][GNU Emacs]] [[https://orgmode.org/][Org Mode]] with [[https://ox-hugo.scripter.co/][ox-hugo]] to make content for
[[https://gohugo.io/][Hugo]].  See [[file:/articles/howido][howido]] if interested in details of my personal computing
configuration.  The source to this site is in my [[https://github.com/brettviren/pub][pub]] repo and though
not likely interesting to humans the exported HTML lands in [[https://github.com/brettviren/brettviren.github.io][this repo]].

* Todo

** templates

- [X] Basic RSS feeds, these are out-of-the-box
- [X] Full content RSS feeds.
- [ ] Two RSS feed variants: ordered by pub date and by last modified date 
- [X] per heading anchor links (as ripped from [[https://github.com/kaushalmodi/hugo-onyx-theme][hugo-onyx-theme]])
- [ ] customize notes list.html
- [ ] sidebar with recents, tags, categories
- [ ] home page with tagclouds and most recent of each section

** deploy

- [X] Deploy to my github
- [X] Deploy to local ~public_html~
- [ ] +Deploy to my BNL via rsync+ wontfix
- [X] automate deployment
- [ ] some kind of comments system?  maybe offload to github discussions with auto thread start based on a deploy?  using GH API and ~hub~?  there's a topic for a post.

** editing

- [X] org mode capture templates
- [ ] org capture for notes

