title = "They call me Brett"
languageCode = "en-us"

### Can give:  hugo --baseURL <url> ...
## Support any host if public/ is mapped to "/" URL
baseURL = "/"
## Or can explicitly give host part
# baseURL = "http://brettviren.github.io/"
## If one needs a URL path:
# baseURL = "http://localhost/~bv/pub/"

## Don't change these.  Need to canonify to support changing baseURL
## to have some extra URL path.
relativeURLs = false
canonifyURLs = true

# theme = "smol"
# theme = "smigle"
# theme = "archie"
# modified version of archie
# theme = "meathead"
# theme = "the-roots-home"


[markup.goldmark.renderer]
  unsafe= true

#pygmentsStyle = "autumn"
#pygmentsStyle = "emacs"
pygmentsStyle = "solarized-light"
pygmentsCodeFences = true
[markup]
  [[highlight]]
        noClasses=false
        codeFences = true
        tabWidth = 4

[params]
    subtitle = "turning neutrinos in to bytes"
    author = "Brett Viren"  
#     dateFmt = "Mon Jan 2 2006"
     dateFmt = "Mon 2 Jan 2006"
#     dateFmt = "2006-01-02"

  [[params.social]]
    url = "https://github.com/brettviren"
    icon = "github"
    name = "Github"
  [[params.social]]
        name = "bv@bnl.gov"
        url = "mailto:bv@bnl.gov"
        icon = "email"
  [[params.social]]
        name = "brett.viren@gmail.com"
        url = "mailto:brett.viren@gmail.com"
        icon = "email"
  [[params.social]]
        name = "keybase"
        url = "https://keybase.io/BrettViren"
        icon = "keybase"
  [[params.social]]
        name = "twitter"
        url = "https://twitter.com/brett_viren"
        icon = "twitter"

  [[params.social]]
        name = "fosstodon"
        url = "https://fosstodon.org/@bv"
        icon = "matrix"

  # [[params.social]]
  #       name = "matrix"
  #       url = "matrix://@bv:matrix.org"
  #       icon = "matrix"



[menu]
  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1 

  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 2

  [[menu.main]]
        identifier = "articles"
        name = "Articles"
        url = "/articles/"
        weight = 3

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 4 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 5

# Footer
  [[menu.footer]]
        name = "bv@bnl.gov"
        url = "mailto:bv@bnl.gov"
        weight = 1 
  [[menu.footer]]
        name = "brett.viren@gmail.com"
        url = "mailto:brett.viren@gmail.com"
        weight = 2
  [[menu.footer]]
        name = "github"
        url = "https://github.com/brettviren"
        weight = 3 
  [[menu.footer]]
        name = "keybase"
        url = "https://keybase.io/BrettViren"
        weight = 4
  [[menu.footer]]
        name = "twitter"
        url = "https://twitter.com/brett_viren"
        weight = 5


